permissions:
  contents: write
  
name: Build and Release .NET Console App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/JottaShift.slnx

      - name: Build
        run: dotnet build src/JottaShift.slnx --configuration Release --no-restore

      - name: Publish
        run: |
            dotnet publish src/JottaShift.Console/JottaShift.Console.csproj \
            -c Release \
            -o ./publish \
            -r win-x64 \
            -p:PublishSingleFile=true \
            -p:SelfContained=true \
            -p:UseAppHost=true

      - name: Archive published output
        id: archive
        run: |
          cd publish
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION_NO_V="${VERSION#v}"
          ZIPNAME="JottaShift-${VERSION_NO_V}.zip"
          zip -r ../${ZIPNAME} .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.archive.outputs.zipname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
